apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: demo
build:
  artifacts:
    - image: ghcr.io/iamnoah/skaffold-tput-colors-bug/baz
      ko:
        main: ./foo
      hooks:
        before:
          - command: [go, mod, vendor]
    - image: ghcr.io/iamnoah/skaffold-tput-colors-bug/foo
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: [go, mod, vendor]
    - image: ghcr.io/iamnoah/skaffold-tput-colors-bug/bar
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: [go, mod, vendor]
