apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: demo
build:
  artifacts:
    - image: baz
      ko:
        main: ./foo
      hooks:
        before:
          - command: [go, mod, vendor]
    - image: foo
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: [go, mod, vendor]
    - image: bar
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: [go, mod, vendor]
